# Generated by Django 5.2.6 on 2025-10-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
