# Generated by Django 5.2.6 on 2025-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите иконку продукта', null=True, upload_to='products/icons', verbose_name='Иконка'),
        ),
    ]
