# Generated by Django 5.2.6 on 2025-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='products/icons', verbose_name='Иконка'),
        ),
    ]
