# Generated by Django 5.2.6 on 2025-10-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Can unpublish Product'), ('can_delete_product', 'Can delete Product')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
