# Generated by Django 5.2.6 on 2025-10-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Может снимать с публикации товар'), ('can_delete_product', 'Может удалять товар'), ('can_publish_product', 'Может публиковать товар')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
